sudo: false
language: go
services:
  - postgresql    
addons:
  postgresql: "9.6" 
before_install:
  - go get github.com/mattn/goveralls
install:
  - go get -v -u github.com/golang/dep/cmd/dep
  - dep ensure
script:
  - $GOPATH/bin/goveralls -service=travis-ci
